# Generated by Django 5.2.1 on 2025-05-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinary_status', models.CharField(choices=[('very_good', 'Very good'), ('good', 'Good'), ('normal', 'Normal'), ('bad', 'Bad'), ('very_bad', 'Very bad')], max_length=255, verbose_name='Discplinary status')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='classroom.classroom')),
            ],
        ),
    ]
