# Generated by Django 5.2 on 2025-04-15 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ClassRoom Name')),
                ('base', models.PositiveIntegerField(verbose_name='Base of student')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field', verbose_name='Field')),
                ('students', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(limit_choices_to={'user_type': 'teacher'}, related_name='teaching_classroom', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
