# Generated by Django 5.2 on 2025-04-17 05:44

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=builtins.print),
            preserve_default=False,
        ),
    ]
